default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: postgres
  host: "localhost"
  port: 5432
  username: "lucas"
  password: "161263"


test:
  <<: *default
  database: tests
  host: "localhost"
  port: 5432
  username: "lucas"
  password: "161263"